---
micronaut:
  application:
    name: micronaut-kafka-avro-v3

---
kafka:
  bootstrap:
    servers: localhost:9092
  schema:
    registry:
      url: http://localhost:8081
  streams:
    default:
      application.id: partner-v3
      processing.guarantee: exactly_once

graphql-factory-config:
  classpath: classpath:schema.graphqls
  schema:
    - Mutation
    - Query

topics:
  partnerTopic: partner-topic
stores:
  partnerStore: partner

---
graphql:
  enabled: true
  graphiql:
    enabled: true
    path: /graphiql